# Generated by Django 5.0 on 2023-12-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PackersMovers_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='betweencitiesbooking',
            name='services',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='withincitybooking',
            name='services',
            field=models.CharField(default='', max_length=255),
        ),
    ]
