# Generated by Django 5.0 on 2023-12-14 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PackersMovers_App', '0002_betweencitiesbooking_services_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='lastname',
        ),
    ]
