# Generated by Django 5.0 on 2023-12-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PackersMovers_App', '0004_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/', verbose_name='Service Image'),
        ),
    ]
