# Generated by Django 5.0 on 2024-03-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PackersMovers_App', '0006_betweencitiesbooking_status_withincitybooking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withincitybooking',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
