# Generated by Django 5.0 on 2024-03-07 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PackersMovers_App', '0007_alter_withincitybooking_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withincitybooking',
            old_name='date',
            new_name='dateofinquiry',
        ),
    ]
