# Generated by Django 5.0 on 2024-03-07 11:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PackersMovers_App', '0008_rename_date_withincitybooking_dateofinquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='betweencitiesbooking',
            name='date',
        ),
        migrations.AddField(
            model_name='betweencitiesbooking',
            name='dateofinquiry',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='betweencitiesbooking',
            name='orderbookeddate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='withincitybooking',
            name='orderbookeddate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='withincitybooking',
            name='dateofinquiry',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
