# Generated by Django 5.0 on 2024-03-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PackersMovers_App', '0009_remove_betweencitiesbooking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betweencitiesbooking',
            name='services',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='withincitybooking',
            name='services',
            field=models.CharField(max_length=100),
        ),
    ]
